- ID: cm-001
  Category: 云安全配置错误
  Created_At: 2025-07-31
  Contributors: 
    - ZacharyRiser
  Additional_Info: |
    - 宝马Azure Blob Storage配置错误事件
    - 攻击者利用了云平台的默认权限继承机制和不安全的配置属性
    - 最终通过REST API调用窃取了JWT私钥等云原生凭证
  Title_CN: 云安全配置错误-Azure存储桶配置不当致凭证泄露
  Title_EN: cloud misconfiguration - azure blob storage leads to credential leakage
  Question: |
    请以SOC团队的指挥官身份，评估并决策以下安全事件：
    - 组织背景：某公司的开发团队正在使用微软Azure云平台，并利用其Blob Storage服务存储配置文件。
    - 事件描述：安全社区披露，因Azure Blob Storage的权限配置错误，导致包含JWT私钥、数据库连接字符串等高敏感信息的配置文件被公开访问。
    - 上下文：该事件的根因是存储桶的`AllowBlobPublicAccess`属性被错误地设置为`true`，同时父级策略也未禁用匿名访问。攻击者利用这一配置缺陷，直接通过REST API调用下载了敏感配置文件，获取了访问云服务的核心凭证。
    
    作为SOC团队的指挥官，请你对安全事件作出评估并决策。
  Complex_CoT: |

  Response: |

# ---
# [Note] Case Study Value:
# 1. 首个“云安全配置错误”案例：本案例是语料库中第一个专注于攻击云平台自身配置而非其上运行的应用的样本。
# 2. 引入“云原生攻击路径”：清晰地展示了攻击者如何利用云平台特有的API和服务（如REST API, 权限继承）进行攻击。
# 3. 聚焦云原生凭证窃取：其攻击目标是云环境下的核心凭证（JWT私钥、连接字符串），与传统OS凭证完全不同。
# 4. 关联MITRE ATT&CK for Cloud：为AI提供了一个将具体云攻击事件与行业标准威胁框架相关联的范例。