- ID: cm-002
  Category: 云安全配置错误
  Created_At: 2025-07-31
  Contributors: 
    - ZacharyRiser
  Additional_Info: |
    - 微软AI团队GitHub数据泄露事件
    - 根因是开发人员生成了权限过高的Azure共享访问签名(SAS)令牌
    - 攻击者通过一个公开的链接即可获得整个存储账户的完全控制权
  Title_CN: 云安全配置错误-Azure SAS令牌权限过高致数据泄露
  Title_EN: cloud misconfiguration - azure sas token over-permission leads to data breach
  Question: |
    请以SOC团队的指挥官身份，评估并决策以下安全事件：
    - 组织背景：微软AI团队，使用GitHub和Azure Storage进行开源代码和AI模型的分享。
    - 事件描述：安全社区披露，微软AI团队在GitHub上意外泄露了一个指向其Azure存储账户的链接，导致超过3万条内部信息面临风险。
    - 上下文：该事件的根因是，开发人员在生成用于分享文件的共享访问签名(SAS)令牌时，错误地赋予了其“完全控制”整个存储账户的权限。攻击者只需点击这个公开在GitHub上的链接，即可利用该令牌随意浏览、删除、甚至上传恶意内容到该存储账户中。
    
    作为SOC团队的指挥官，请你对安全事件作出评估并决策。
  Complex_CoT: |

  Response: |

# ---
# [Note] Case Study Value:
# 1. 引入SAS令牌配置风险：本案例的核心是展示了因生成权限过高的临时授权凭证(SAS Token)而导致的严重安全事件，与cm-001的静态配置错误形成互补。
# 2. “最小权限原则”的反面教材：完美诠释了在云环境中，违反最小权限原则会带来多么直接和严重的后果。
# 3. GitHub作为泄露入口：清晰地展示了源代码管理平台是如何成为泄露云基础设施访问入口的源头。